language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python setup.py sdist

deploy:
  provider: pypi
  username: '__token__'
  password: $PYPI_TOKEN
  on:
    tags: true